# Generated by Django 3.1.7 on 2021-03-30 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bluetoothdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluetoothdevice',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 1, 36, 52, 40449)),
        ),
        migrations.AlterField(
            model_name='bluetoothdevice',
            name='device_type',
            field=models.CharField(choices=[('BS', 'Bluetooth Speakers'), ('PH', 'Phone'), ('HS', 'Headset'), ('IOT', 'Internet of Things')], max_length=3),
        ),
    ]
