# Generated by Django 3.1.7 on 2021-04-20 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210411_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('service_classes', models.CharField(max_length=100)),
                ('profiles', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
