# Generated by Django 3.1.7 on 2021-04-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210420_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluetoothservice',
            name='sensor',
            field=models.CharField(default='laptopsensor', max_length=100),
        ),
    ]
