# Generated by Django 3.1.7 on 2021-10-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bluetoothdevice_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvetable',
            old_name='cvename',
            new_name='cve_id',
        ),
        migrations.AddField(
            model_name='cvetable',
            name='cve_description',
            field=models.CharField(default='CVE-1000', max_length=500),
            preserve_default=False,
        ),
    ]
