# Generated by Django 3.1.7 on 2021-10-11 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211007_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerableTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('cve_vulnerability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cvetable')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bluetoothdevice')),
            ],
        ),
    ]
