# Generated by Django 3.1.7 on 2021-04-11 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210329_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluetoothdevice',
            name='sensor',
            field=models.CharField(default='officeraspberry', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bluetoothdevice',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
