# Generated by Django 3.1.7 on 2021-10-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_vulnerabletable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvetable',
            name='cve_description',
            field=models.TextField(max_length=500),
        ),
    ]
